codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/tests/**"
  - "**/examples/**"
  - "**/*.config.*"
  - "**/dist/**"

flags:
  argo-core:
    paths:
      - packages/argo-core/src/
    carryforward: true
  argo-cli:
    paths:
      - packages/argo-cli/src/
    carryforward: true
  argo-excel:
    paths:
      - packages/argo-excel/src/
    carryforward: true
